language: go

go:
  - "1.10.x"

before_install:
  - mysql -e 'CREATE DATABASE test;'

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get ./...

script:
  - go test -v ./...

services:
  - mysql
