language: go

go:
  - "1.10.x"

env:
  global:
    secure: "FvrwzhyMp0odARc/Gw+mKtncIJJOrfzAlvzT23dvz5/Z81AOkc0MwMPLbHvDo19+x0gSfyJJ8MM46vOHs2sh86W8f/RYMhbJVkVp7Ds6wk6Ktyxq7V1Hm9U7VXA2yup/dt6exyxQUj051sIEt6g8XX5rNq49yQJ2+calGy0QOxd4N8BqVZHD4UzmiBPGpWxdXZDa5sVq1tJNH2+gXOork3e6ZtJfHphmp4G8OruVKC2BpGTICyyH8Jj9MSpcL80etQSobEJ78IafPVosKnvQW3JcyozGx6aesttzAKYcNiejey5XDhE/A55ZJsOCXPnEvZxUih9etXn3kCW+lk/UxDbXNWrS8bHmdysKJUoUTWQcFZEDc8/csNRnF27WEqtOIQEOR3/irsrjlfUTxyeRuCrI4+w+KnI37/lg7YA+9bOYY/n7duE89K0ZX2S36+4Jgj+KA3KEc0RYtCwWQ4vH+8e744LCiEE8C4jo2Y6CvpQjBBXa0Isns+jS1xNGKCodFeZmlyWU7s6XYrmKD/hbVMbG9XBFY3xmIZshJnj64Igw70e3qoXB4ne5xdPyn+TODaEucVBIuDBl+9jqB6RGE6/QETMHCqXCqGbDv0o4Mi/ukDoqWWh4Ooizr6wwVc2WicWPZWfNdNh3/souz2RpD5329WBNkGZ7LVmoBTJBDPA="

before_install:
  - mysql -e 'CREATE DATABASE test;'

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get ./...

script:
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

services:
  - mysql

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Lucsa Pearson"
  - git config --local user.email "catdevman@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - go build main.go
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "main"
  skip_cleanup: true
  on:
    tags: true

after_success:
  bash <(curl -s https://codecov.io/bash)
